version: '3.8'

services:
  db:
    image: postgres:16.4
    container_name: fastapi_db
    environment:
      POSTGRES_USER: vusht
      POSTGRES_PASSWORD: 150220
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-network

  web:
    build:
      context: ./  
      dockerfile: Dockerfile  
    container_name: fastapi-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"  
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

volumes:
  postgres_data:
